package com.meadow.feature.script.data.local

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.util.UUID

@Entity(
    tableName = "script_variants",
    indices = [
        Index(value = ["scriptId"]),
        Index(value = ["language"]),
        Index(value = ["lastEditedAt"])
    ]
)
data class ScriptVariantEntity(
    @PrimaryKey
    val variantId: String = UUID.randomUUID().toString(),

    val scriptId: String,
    val language: String,
    val content: String,
    val isAutoGenerated: Int,
    val sourceVariantId: String?,
    val lastEditedAt: Long
)
