package com.meadow.feature.script.data.repository

import com.meadow.feature.script.data.local.ScriptEntity
import com.meadow.feature.script.data.local.ScriptVariantEntity
import com.meadow.feature.script.domain.model.Script
import com.meadow.feature.script.domain.model.ScriptDialect
import com.meadow.feature.script.domain.model.ScriptParent
import com.meadow.feature.script.domain.model.ScriptParentType
import com.meadow.feature.script.domain.model.ScriptType
import com.meadow.feature.script.domain.model.ScriptVariant
import java.time.Instant

internal fun ScriptEntity.toDomain(): Script {
    val parent = when (ScriptParentType.valueOf(parentType)) {
        ScriptParentType.PROJECT -> ScriptParent.Project(projectId = requireNotNull(projectId))
        ScriptParentType.SERIES -> ScriptParent.Series(seriesId = requireNotNull(seriesId))
        ScriptParentType.PROJECT_IN_SERIES -> ScriptParent.ProjectInSeries(
            projectId = requireNotNull(projectId),
            seriesId = requireNotNull(seriesId)
        )
    }

    return Script(
        scriptId = scriptId,
        parent = parent,
        seasonId = seasonId,
        type = ScriptType.valueOf(type),
        dialect = ScriptDialect.valueOf(dialect),
        canonicalLanguage = canonicalLanguage,
        createdAt = Instant.ofEpochMilli(createdAt),
        updatedAt = Instant.ofEpochMilli(updatedAt)
    )
}

internal fun ScriptVariantEntity.toDomain(): ScriptVariant {
    return ScriptVariant(
        variantId = variantId,
        scriptId = scriptId,
        language = language,
        content = content,
        isAutoGenerated = isAutoGenerated == 1,
        sourceVariantId = sourceVariantId,
        lastEditedAt = Instant.ofEpochMilli(lastEditedAt)
    )
}
