package com.meadow.feature.script.data.repository

import com.meadow.feature.script.data.local.ScriptDao
import com.meadow.feature.script.data.local.ScriptEntity
import com.meadow.feature.script.data.local.ScriptVariantDao
import com.meadow.feature.script.data.local.ScriptVariantEntity
import com.meadow.feature.script.domain.model.ScriptDialect
import com.meadow.feature.script.domain.model.ScriptParentType
import com.meadow.feature.script.domain.model.ScriptType
import com.meadow.feature.script.domain.model.ScriptVariant
import com.meadow.feature.script.domain.repository.ScriptRepositoryContract
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ScriptRepository @Inject constructor(
    private val scriptDao: ScriptDao,
    private val variantDao: ScriptVariantDao
) : ScriptRepositoryContract {

    override fun observeScriptsByProject(
        projectId: String
    ) = scriptDao.observeScriptsByProject(projectId).map { list ->
        list.map { it.toDomain() }
    }

    override suspend fun createScriptForProject(
        projectId: String,
        type: ScriptType,
        dialect: ScriptDialect,
        canonicalLanguage: String
    ): String {
        val now = System.currentTimeMillis()
        val scriptId = UUID.randomUUID().toString()

        val entity = ScriptEntity(
            scriptId = scriptId,
            parentType = ScriptParentType.PROJECT.name,
            projectId = projectId,
            seriesId = null,
            seasonId = null,
            type = type.name,
            dialect = dialect.name,
            canonicalLanguage = canonicalLanguage,
            createdAt = now,
            updatedAt = now,
            localUpdatedAt = now,
            isDirty = 1
        )

        scriptDao.upsert(entity)
        ensureCanonicalVariant(scriptId = scriptId, language = canonicalLanguage)
        return scriptId
    }

    override suspend fun getScript(
        scriptId: String
    ) = scriptDao.getScript(scriptId)?.toDomain()

    override fun observeVariants(
        scriptId: String
    ): Flow<List<ScriptVariant>> {
        return variantDao.observeVariants(scriptId).map { list ->
            list.map { it.toDomain() }
        }
    }

    override suspend fun getVariant(
        variantId: String
    ): ScriptVariant? {
        return variantDao.getVariant(variantId)?.toDomain()
    }

    override suspend fun upsertVariantContent(
        variantId: String,
        content: String
    ) {
        val existing = variantDao.getVariant(variantId) ?: return
        val now = System.currentTimeMillis()
        variantDao.upsert(
            existing.copy(
                content = content,
                lastEditedAt = now
            )
        )
    }

    override suspend fun ensureCanonicalVariant(
        scriptId: String,
        language: String
    ): String {
        val existing = variantDao.getVariantByScriptAndLanguage(scriptId, language)
        if (existing != null) return existing.variantId

        val now = System.currentTimeMillis()
        val variantId = UUID.randomUUID().toString()
        val entity = ScriptVariantEntity(
            variantId = variantId,
            scriptId = scriptId,
            language = language,
            content = "",
            isAutoGenerated = 0,
            sourceVariantId = null,
            lastEditedAt = now
        )
        variantDao.upsert(entity)
        return variantId
    }
}
