package com.meadow.feature.script.domain.model

import java.time.Instant

data class ScriptVariant(
    val variantId: String,
    val scriptId: String,
    val language: LanguageCode,
    val content: String,
    val isAutoGenerated: Boolean,
    val sourceVariantId: String?,
    val lastEditedAt: Instant
)
